name: PingTabList
version: '1.4'
main: com.diabloiiiros.PingTabList.Main
api-version: 1.17
authors: [diabloIIIROS]
description: Shows all players ping numbers in the tab list
permissions:
  pingtl.reload:
    default: false
    description: Permission to reload the config.yml
  pingtl.ping:
    default: false
    description: Permission to have players see there ping number in the tab list
commands:
  pingtl:
    description: Reload command for config.yml
    usage: /<command>
